### PR TITLE
pyspnego kerberos dependencies

### PR DESCRIPTION
**Pull request by blabalme**
https://github.com/jborean93/pyspnego/blob/cba319d9795148702ce6d5575f13508a12fab4ec/pyproject.toml#L33

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@blabalme, as the linter is showing, if you want to add platform-specific runtime requirements, you will need to _remove_ the `noarch: python` line, and then regenerate the feedstock to build separate packages for each platform (and each python version).

**Comment by blabalme** [comment]
> @blabalme, as the linter is showing, if you want to add platform-specific runtime requirements, you will need to _remove_ the `noarch: python` line, and then regenerate the feedstock to build separate packages for each platform (and each python version).

Thanks for the help. I'm trying to reproduce the dependence of the pip package as closely as possible: https://github.com/jborean93/pyspnego/blob/cba319d9795148702ce6d5575f13508a12fab4ec/pyproject.toml#L33

**Comment by blabalme** [comment]
@duncanmmacleod 
I'm not sure what I did.
I wanted to make an equivalent of `pip install pyspnego[Kerberos]`. Without the kerberos option I have missing module krb5 and gssapi errors on linux.
I based myself on this doc: https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-packages-with-os-specific-dependencies

**Comment by duncanmmacleod** [comment]
@conda-forge-admin, please rerender

**Comment by duncanmmacleod** [comment]
@blabalme, I was blissfully unaware of the (new?) syntax for platform-dependent noarch packages, thank you for posting that link, and thanks for updating this project!

I think this should be fine just as soon as the CI configuration has been updated and tested to include a separate 'noarch' build for Windows.

**Review by duncanmmacleod — APPROVED** [review]

**Pull request merged**
